version: '2'

services:
  api:
<<<<<<< HEAD
    ports:
      - 9000:9000
=======
>>>>>>> fece6203126de77be60ef7a76cf08897ee1fbd7d
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        STATIC_URL: '/static/'
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    volumes:
<<<<<<< HEAD
      - ./:/app:cached
      - /app/node_modules/
    command: npm start -- --host 0.0.0.0
=======
      - ./saleor/:/app/saleor:Z
      - ./templates/:/app/templates:Z
      - ./tests/:/app/tests
>>>>>>> fece6203126de77be60ef7a76cf08897ee1fbd7d
    env_file: common.env
    environment:
      - JAEGER_AGENT_HOST=jaeger      
      - STOREFRONT_URL=http://localhost:3000/
      - DASHBOARD_URL=http://localhost:9000/


  worker:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
      args:
        STATIC_URL: '/static/'
    restart: unless-stopped
    networks:
      - saleor-backend-tier
    command: npm start -- --host 0.0.0.0
    env_file: common.env
    volumes:
      - ./:/app:cached
      - /app/node_modules/


volumes:
  saleor-db:
    driver: local
  saleor-redis:
    driver: local
  saleor-media:

networks:
  saleor-backend-tier:
    driver: bridge
  

